from langchain_community.chat_models import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

from src.utils.utils import format_question

class ArticleKnowledgeGenerator:
    system_prompt = """
    You will be provided with an exam question that concerns the Polish Civil Code. 
    The exam question may be either a direct question or an incomplete sentence, accompanied by three potential answers labeled a, b, and c. 
    Your task is to analyze the question and return a list of specific Civil Code articles that are most relevant and useful in selecting the correct answer. 
    You can choose how many articles you like. It is better to select more than less. If the needed article won't be selected this would lead to system failure.
    When redundant articles are selected this won't have large consequences.
    Respond in polish
    Return the scope of articles as their numbers in in format: [<number>-<number>].
    For example: [1-7].
    
    Base your responses on the following table of contents of Polish Civil Code:
   Art. 1.-Art. 7.
Przepisy wstępne kodeksu cywilnego, które definiują podstawowe zasady regulujące stosunki cywilnoprawne między osobami fizycznymi i prawnymi. Zawierają kluczowe zasady dotyczące mocy wstecznej przepisów, ograniczeń w korzystaniu z praw, obowiązku udowodnienia faktów oraz domniemania dobrej wiary w kontekście skutków prawnych.
Art. 8.-Art. 24.
Przepisy dotyczące zdolności prawnej i zdolności do czynności prawnych, które określają, kto ma prawo do podejmowania działań prawnych oraz w jakich okolicznościach. Zawierają definicje pełnoletności, ubezwłasnowolnienia, a także zasady dotyczące umów zawieranych przez osoby z ograniczoną zdolnością do czynności prawnych. Dodatkowo, regulują ochronę dóbr osobistych oraz możliwości dochodzenia roszczeń w przypadku ich naruszenia.
Art. 25.-Art. 28.
Przepisy dotyczące miejsca zamieszkania w Kodeksie cywilnym, które definiują, czym jest miejsce zamieszkania osoby fizycznej oraz zasady ustalania miejsca zamieszkania dzieci i osób pod opieką. Określają, że każda osoba może mieć tylko jedno miejsce zamieszkania, a w przypadku dzieci i osób pod opieką, miejsce to jest związane z rodzicami lub opiekunami.
Art. 29.-Art. 32.
Przepisy dotyczące uznania zaginionego za zmarłego, które określają warunki i procedury związane z tym procesem. Zawierają zasady dotyczące upływu czasu niezbędnego do uznania zaginionego za zmarłego w różnych okolicznościach, takich jak zaginienie w wyniku katastrofy czy bezpośredniego niebezpieczeństwa. Określają również moment domniemanej śmierci oraz sytuacje, w których kilka osób może być uznanych za zmarłe jednocześnie.
Art. 33.-Art. 43.
Przepisy dotyczące osób prawnych w Kodeksie cywilnym, które definiują status prawny, odpowiedzialność oraz zasady działania osób prawnych, w tym Skarbu Państwa i jednostek organizacyjnych. Zawierają regulacje dotyczące powstawania, ustroju, reprezentacji oraz odpowiedzialności osób prawnych, a także zasady dotyczące kuratora w przypadku braku organu reprezentującego. Przepisy te mają na celu zapewnienie jasności w zakresie praw i obowiązków osób prawnych w obrocie prawnym.
Art. 431.-Art. 4310.
Przepisy dotyczące przedsiębiorców w Kodeksie cywilnym, które definiują pojęcie przedsiębiorcy oraz zasady dotyczące prowadzenia działalności gospodarczej pod firmą. Zawierają regulacje dotyczące nazewnictwa firm, ich rejestracji, wymogów dotyczących odróżniania firm na rynku, a także zasady dotyczące zmiany i ochrony praw do firmy. Przepisy te określają również zasady dotyczące zbywania firmy oraz ochrony przed naruszeniem praw do firmy przez osoby trzecie.
Art. 44.-Art. 554.
Przepisy dotyczące mienia, własności oraz praw majątkowych w Kodeksie cywilnym. Zawierają definicje mienia, nieruchomości, przynależności oraz pożytków, a także regulacje dotyczące przedsiębiorstw i gospodarstw rolnych. Określają zasady dotyczące własności, odpowiedzialności za zobowiązania związane z nabyciem przedsiębiorstw oraz szczegółowe przepisy dotyczące części składowych rzeczy i ich przynależności.
Art. 56.-Art. 651.
Przepisy dotyczące czynności prawnych i oświadczeń woli w Kodeksie cywilnym. Zawierają zasady dotyczące skutków czynności prawnych, ich ważności, wyrażania woli oraz wymogów formalnych. Określają również zasady dotyczące zgody osób trzecich oraz interpretacji oświadczeń woli, a także skutki prawne związane z nieważnością czynności prawnych.
Art. 66.-Art. 721.
Przepisy dotyczące składania ofert oraz zawierania umów w polskim prawie cywilnym. Zawierają zasady dotyczące definicji oferty, jej przyjęcia, odwołania oraz skutków związanych z negocjacjami. Obejmują również szczególne regulacje dotyczące ofert składanych w formie elektronicznej oraz w kontekście aukcji i przetargów. Przepisy te określają również zasady dotyczące poufności informacji w trakcie negocjacji oraz odpowiedzialności za naruszenie dobrych obyczajów w procesie zawierania umów.
Art. 73.-Art. 81.
Przepisy dotyczące formy czynności prawnych w Kodeksie cywilnym, które określają zasady dotyczące ważności i skutków prawnych czynności dokonanych w określonej formie. Zawierają regulacje dotyczące formy pisemnej, dokumentowej i elektronicznej, a także szczególne wymagania dla zbycia przedsiębiorstw oraz zasady dotyczące dowodów w przypadku niezachowania wymaganej formy. Przepisy te wskazują również na możliwość potwierdzenia umowy przez strony oraz na zasady dotyczące osób niemogących pisać.
Art. 82.-Art. 88.
Przepisy dotyczące nieważności oświadczeń woli w Kodeksie cywilnym, które regulują sytuacje, w których oświadczenia te mogą być uznane za nieważne. Zawierają zasady dotyczące braku zdolności do działania (np. w wyniku choroby psychicznej), pozorności oświadczeń, błędów w treści czynności prawnej, zniekształcenia oświadczeń oraz wpływu groźby na ważność oświadczenia. Przepisy te określają również procedury uchwały od skutków prawnych oraz terminy na zgłaszanie takich uchwał.
Art. 89.-Art. 94.
Przepisy dotyczące warunków w czynnościach prawnych, które regulują zasady uzależniania skutków prawnych od zdarzeń przyszłych i niepewnych. Zawierają informacje na temat mocy wstecznej ziszczenia się warunku, uprawnień warunkowo uprawnionych, skutków dla rozporządzeń prawnych w przypadku ziszczenia się warunku oraz konsekwencji działań sprzecznych z zasadami współżycia społecznego w kontekście warunków. Określają również zasady dotyczące nieważności czynności prawnej w przypadku niemożliwych lub sprzecznych z prawem warunków.
Art. 95.-Art. 97.
Przepisy dotyczące przedstawicielstwa w polskim prawie cywilnym, które regulują zasady dokonywania czynności prawnych przez przedstawicieli. Zawierają informacje na temat umocowania do działania w cudzym imieniu, zarówno w kontekście przedstawicielstwa ustawowego, jak i pełnomocnictwa, a także wskazują na domniemanie umocowania osób działających w lokalach przedsiębiorstw obsługujących publiczność.
Art. 98.-Art. 109.
Przepisy dotyczące pełnomocnictwa w Kodeksie cywilnym, które regulują zasady udzielania, zakresu oraz skutków prawnych pełnomocnictw. Zawierają informacje na temat formy pełnomocnictwa, możliwości jego odwołania, skutków działania pełnomocnika bez umocowania, a także zasady dotyczące ustanawiania pełnomocników przez pełnomocnika. Przepisy te określają również zasady dotyczące ważności czynności prawnych dokonywanych w imieniu mocodawcy oraz sytuacje, w których pełnomocnik może działać w imieniu mocodawcy.
Art. 1091.-Art. 1098.
Przepisy dotyczące prokury w Kodeksie cywilnym, które regulują zasady udzielania pełnomocnictwa przez przedsiębiorców. Zawierają informacje na temat formy prokury, jej zakresu, możliwości ograniczeń, a także zasad dotyczących odwołania i wygaśnięcia prokury. Określają również obowiązki przedsiębiorcy związane z zgłaszaniem prokury do odpowiednich rejestrów.
Art. 110.-Art. 116.
Przepisy dotyczące obliczania terminów w polskim prawie cywilnym. Zawierają zasady dotyczące końca terminów oznaczonych w dniach, tygodniach, miesiącach i latach, a także regulacje dotyczące dni wolnych od pracy oraz szczególne przypadki związane z terminami związanymi z czynnościami prawnymi. Umożliwiają one precyzyjne ustalenie momentu, w którym terminy wygasają lub skutki czynności prawnych mają miejsce.
Art. 117.-Art. 125.
Przepisy dotyczące przedawnienia roszczeń majątkowych w Kodeksie cywilnym. Zawierają zasady dotyczące terminów przedawnienia, ich zawieszenia oraz przerwania, a także szczególne regulacje dotyczące roszczeń przysługujących konsumentom i osobom niepełnosprawnym. Określają również, w jakich sytuacjach sąd może nie uwzględnić upływu terminu przedawnienia oraz zasady dotyczące rozpoczęcia biegu przedawnienia.
Art. 140.-Art. 154.
Przepisy dotyczące prawa własności i korzystania z nieruchomości, które określają prawa i obowiązki właścicieli gruntów oraz zasady współżycia sąsiedzkiego. Zawierają regulacje dotyczące korzystania z rzeczy, ochrony przed szkodami, zasadności ustanawiania służebności drogowej, a także kwestie związane z granicami gruntów, współdziałaniem sąsiadów przy rozgraniczeniu oraz wspólnym użytkowaniem urządzeń granicznych. Przepisy te mają na celu zapewnienie harmonijnego współżycia właścicieli nieruchomości oraz ochronę ich praw.
Art. 155.-Art. 170.
Przepisy dotyczące przeniesienia własności rzeczy, zarówno ruchomych, jak i nieruchomości, w polskim prawie cywilnym. Zawierają zasady dotyczące umów sprzedaży, zamiany, darowizny oraz warunków przeniesienia własności, w tym wymogi dotyczące formy umowy dla nieruchomości. Regulują również kwestie związane z prawem pierwokupu dla współwłaścicieli nieruchomości rolnej oraz zasady dotyczące nabycia własności przez osoby nieuprawnione. Wskazują na znaczenie dobrej wiary w transakcjach oraz skutki obciążenia rzeczy prawem osoby trzeciej.
Art. 172.-Art. 176.
Przepisy dotyczące zasiedzenia, które regulują nabywanie własności nieruchomości i rzeczy ruchomych przez posiadaczy, którzy nie są ich właścicielami. Zawierają zasady dotyczące długości posiadania, wpływu złej wiary na nabycie własności, a także szczególne przepisy dotyczące małoletnich właścicieli oraz przenoszenia posiadania.
Art. 179.-Art. 194.
Przepisy dotyczące nabywania i utraty własności rzeczy ruchomych, w tym zasady dotyczące porzucenia rzeczy, nabycia własności przez objęcie w posiadanie, a także regulacje dotyczące rzeczy znalezionych. Zawierają również przepisy dotyczące współwłasności w przypadku połączenia lub pomieszania rzeczy oraz zasady dotyczące wytwarzania nowych rzeczy z cudzych materiałów.
Art. 195.-Art. 221.
Przepisy dotyczące współwłasności w Kodeksie cywilnym, które regulują zasady posiadania i zarządzania rzeczą wspólną przez kilku współwłaścicieli. Zawierają definicje współwłasności, zasady dotyczące zarządzania, podejmowania decyzji oraz zniesienia współwłasności, w tym szczególne przepisy dotyczące gospodarstw rolnych. Określają również prawa i obowiązki współwłaścicieli, w tym zasady podziału pożytków oraz możliwość żądania spłat w przypadku zniesienia współwłasności.
Art. 222.-Art. 231.
Przepisy dotyczące ochrony własności oraz praw i obowiązków posiadaczy rzeczy. Zawierają regulacje dotyczące roszczeń właściciela wobec osób, które faktycznie władają jego rzeczą, zasady dotyczące przedawnienia tych roszczeń, a także prawa i obowiązki samoistnych posiadaczy w dobrej i złej wierze. Przepisy te określają również zasady dotyczące zwrotu nakładów oraz sytuacje, w których posiadacze mogą żądać przeniesienia własności zajętej działki w przypadku wzniesienia na niej budynków lub innych urządzeń.
Art. 232.-Art. 243.
Przepisy dotyczące użytkowania wieczystego gruntów Skarbu Państwa oraz jednostek samorządu terytorialnego. Regulacje te określają zasady oddawania gruntów w użytkowanie wieczyste, prawa i obowiązki użytkowników, a także kwestie związane z przenoszeniem użytkowania, opłatami oraz warunkami korzystania z gruntów. Zawierają również przepisy dotyczące przedłużania umowy użytkowania wieczystego oraz możliwości rozwiązania umowy w przypadku niewłaściwego korzystania z gruntu.
Art. 244.-Art. 251.
Przepisy dotyczące ograniczonych praw rzeczowych, które obejmują takie prawa jak użytkowanie, służebność, zastaw, spółdzielcze własnościowe prawo do lokalu oraz hipoteka. Zawierają zasady dotyczące ustanawiania, przenoszenia, wygasania oraz zmiany treści tych praw, a także regulacje dotyczące pierwszeństwa w przypadku obciążenia tej samej rzeczy wieloma prawami. Przepisy te wskazują również na konieczność stosowania odpowiednich form prawnych, takich jak umowy i wpisy do ksiąg wieczystych, oraz na zasady ochrony tych praw.
Art. 252.-Art. 265.
Przepisy dotyczące użytkowania rzeczy w Kodeksie cywilnym, które regulują zasady korzystania z rzeczy oraz praw związanych z użytkowaniem. Zawierają informacje na temat obciążania rzeczy prawem do jej używania, ograniczeń w zakresie użytkowania, niezbywalności tego prawa, obowiązków użytkownika oraz właściciela, a także zasad dotyczących napraw, zwrotu rzeczy po wygaśnięciu użytkowania oraz roszczeń między stronami. Przepisy te obejmują również możliwość użytkowania praw.
Art. 266.-Art. 270.
Przepisy dotyczące użytkowania rzeczy, które regulują prawa i obowiązki użytkownika oraz właściciela. Zawierają zasady dotyczące wygasania użytkowania, obowiązki użytkownika w zakresie zachowania substancji rzeczy, możliwość budowy nowych urządzeń, a także procedury zabezpieczenia roszczeń oraz odmowy wydania przedmiotów w przypadku nieprawidłowego użytkowania.
Art. 271.-Art. 279.
Przepisy dotyczące użytkowania gruntów Skarbu Państwa przez rolnicze spółdzielnie produkcyjne. Zawierają zasady dotyczące ustanawiania użytkowania gruntów, przekazywania budynków i urządzeń, a także regulacje dotyczące własności tych obiektów. Określają również zasady dotyczące wygaśnięcia użytkowania oraz możliwości zmiany przeznaczenia gruntów przez spółdzielnie. Dodatkowo, przepisy te odnoszą się do wniesienia wkładów gruntowych przez członków spółdzielni oraz ich skutków prawnych.
Art. 284.-Art. 284.
Przepis dotyczący użytkowania przez osoby prawne, który wskazuje na stosowanie ogólnych zasad z rozdziału I i II, chyba że istnieją odrębne regulacje. Umożliwia to elastyczne podejście do przepisów w kontekście użytkowania, zapewniając jednocześnie, że w przypadku braku specyficznych regulacji, zastosowanie mają ogólne zasady.
Art. 285.-Art. 295.
Przepisy dotyczące służebności gruntowej, które regulują zasady obciążania nieruchomości na rzecz właściciela innej nieruchomości. Zawierają definicje służebności, zasady jej ustanawiania, wykonywania oraz znoszenia. Określają również obowiązki właścicieli nieruchomości władnącej i obciążonej, a także warunki, w jakich służebność może być zmieniana lub wygasać. Przepisy te uwzględniają również kwestie związane z podziałem nieruchomości oraz nabywaniem służebności przez zasiedzenie.
Art. 296.-Art. 305.
Przepisy dotyczące służebności osobistych, które regulują prawa i obowiązki związane z obciążeniem nieruchomości na rzecz określonej osoby fizycznej. Zawierają zasady dotyczące ustanawiania, wykonywania oraz wygasania służebności osobistych, a także ich niezbywalności. Określają również warunki korzystania z nieruchomości przez osoby uprawnione oraz możliwość zmiany sposobu wykonywania służebności w przypadku rażących uchybień.
Art. 3051.-Art. 3054.
Przepisy dotyczące służebności przesyłu, które regulują zasady obciążania nieruchomości na rzecz przedsiębiorców w celu korzystania z urządzeń infrastrukturalnych. Zawierają przepisy dotyczące ustanawiania służebności, wynagrodzenia za jej ustanowienie, przechodzenia służebności na nabywców oraz obowiązków przedsiębiorcy po wygaśnięciu służebności. Dodatkowo, wskazują na zastosowanie przepisów o służebnościach gruntowych w kontekście służebności przesyłu.
Art. 306.-Art. 326.
Przepisy dotyczące zastawu w Kodeksie cywilnym, które regulują zasady ustanawiania i egzekwowania zastawu na rzeczach ruchomych. Zawierają informacje o warunkach ustanowienia zastawu, jego skutkach prawnych, prawach zastawnika i zastawcy, a także o procedurach związanych z zaspokojeniem wierzytelności zabezpieczonej zastawem. Obejmują również kwestie dotyczące przenoszenia wierzytelności oraz skutków związanych z obciążeniem rzeczy innymi prawami.
Art. 327.-Art. 335.
Przepisy dotyczące zastawu na prawach, które regulują zasady ustanawiania i wykonywania zastawu na zbywalnych prawach, w tym wierzytelnościach. Zawierają informacje o formie umowy zastawu, prawach zastawnika i zastawcy, a także procedurach związanych z dochodzeniem roszczeń oraz przejściem zastawu na przedmiot świadczenia.
Art. 336.-Art. 352.
Przepisy dotyczące posiadania rzeczy w Kodeksie cywilnym, które definiują różne formy posiadania, w tym posiadanie samoistne i zależne, oraz zasady ochrony posiadania. Zawierają domniemania dotyczące posiadania, prawa posiadacza do obrony przed samowolnym naruszeniem, a także regulacje dotyczące przenoszenia posiadania. Obejmują również szczególne przepisy dotyczące posiadania służebności oraz roszczenia związane z naruszeniem posiadania.
Art. 353.-Art. 3651.
Przepisy dotyczące zobowiązań w Kodeksie cywilnym, które określają zasady dotyczące powstawania, wykonywania oraz skutków zobowiązań. Zawierają regulacje dotyczące treści i celu świadczeń, staranności dłużnika, możliwości żądania osobistego świadczenia, jakości świadczeń, a także zasady dotyczące odszkodowań i odpowiedzialności za szkody. Przepisy te również regulują kwestie związane z walutą świadczeń oraz odsetkami, a także zasady dotyczące wyboru świadczenia w przypadku zobowiązań przemiennych.
Art. 366.-Art. 378.
Przepisy dotyczące solidarności w zobowiązaniach, które regulują sytuacje, w których kilku dłużników lub wierzycieli jest zobowiązanych do spełnienia świadczeń. Zawierają zasady dotyczące odpowiedzialności dłużników i wierzycieli, możliwość dochodzenia roszczeń, a także skutki działań jednego z dłużników lub wierzycieli na pozostałych. Przepisy te określają również zasady zwrotu świadczeń oraz skutki zwolnienia z długu w kontekście solidarności.
Art. 379.-Art. 383.
Przepisy dotyczące zobowiązań cywilnych w przypadku wielu dłużników i wierzycieli, w tym zasady podziału świadczeń oraz odpowiedzialności dłużników. Określają, kiedy świadczenie jest podzielne, zasady odpowiedzialności dłużników za świadczenia niepodzielne oraz prawa wierzycieli w sytuacji, gdy jest ich kilku. Zawierają również regulacje dotyczące skutków zwolnienia dłużnika z długu oraz odpowiedzialności wierzycieli w przypadku przyjęcia świadczenia przez jednego z nich.
Art. 3831.-Art. 396.
Przepisy dotyczące umów w Kodeksie cywilnym, które regulują zasady zawierania umów, w tym umów z konsumentami oraz postanowienia wzorców umowy. Zawierają przepisy dotyczące ograniczeń w żądaniu dodatkowych opłat przez przedsiębiorców, zasady dotyczące wzorców umowy, w tym ich wiążący charakter oraz zasady dotyczące niedozwolonych postanowień umownych. Obejmują również regulacje dotyczące umów przedwstępnych, odpowiedzialności za niewykonanie umowy oraz zasady odstąpienia od umowy.
Art. 405.-Art. 414.
Przepisy dotyczące bezpodstawnego wzbogacenia oraz świadczenia nienależnego w Kodeksie cywilnym. Reguluje zasady odpowiedzialności za uzyskanie korzyści majątkowej bez podstawy prawnej, w tym obowiązek zwrotu korzyści oraz warunki, w jakich można żądać zwrotu nakładów. Zawiera również przepisy dotyczące sytuacji, w których świadczenie jest nienależne oraz okoliczności, w których zwrot świadczenia nie jest możliwy. Dodatkowo, omawia kwestie związane z przepadkiem świadczenia na rzecz Skarbu Państwa oraz roszczenia z gier i zakładów.
Art. 415.-Art. 449.
Przepisy dotyczące odpowiedzialności deliktowej w Kodeksie cywilnym, które regulują zasady naprawienia szkody wyrządzonej czynem niedozwolonym. Zawierają ogólne zasady odpowiedzialności za szkody, w tym odpowiedzialność osób prawnych, zasady dotyczące działania w obronie koniecznej, odpowiedzialność za szkody wyrządzone przez zwierzęta oraz szczegółowe regulacje dotyczące przedawnienia roszczeń. Przepisy te określają również zasady przyznawania odszkodowań i zadośćuczynienia za doznane krzywdy, w tym w przypadku uszkodzenia ciała, śmierci poszkodowanego oraz naruszenia dóbr osobistych.
Art. 4491.-Art. 44910.
Przepisy dotyczące odpowiedzialności producentów za szkody wyrządzone przez produkty niebezpieczne. Zawierają definicje produktów, zasady odpowiedzialności producentów oraz warunki, w jakich mogą być zwolnieni z tej odpowiedzialności. Określają również zasady dotyczące przedawnienia roszczeń oraz wyłączenia odpowiedzialności, a także wskazują na solidarność odpowiedzialności w przypadku współudziału innych osób. Przepisy te mają na celu ochronę konsumentów przed szkodami wynikającymi z używania niebezpiecznych produktów.
Art. 450.-Art. 470.
Przepisy dotyczące spełnienia świadczeń w ramach zobowiązań cywilnych. Zawierają zasady dotyczące przyjmowania świadczeń, wskazywania długów przez dłużnika, miejsca i terminu spełnienia świadczenia, a także kwestie związane z pokwitowaniem oraz depozytem sądowym. Reguluje również sytuacje, w których dłużnik może złożyć przedmiot świadczenia do depozytu oraz skutki takiego działania.
Art. 471.-Art. 486.
Przepisy dotyczące odpowiedzialności dłużnika za niewykonanie lub nienależyte wykonanie zobowiązań. Zawierają zasady dotyczące naprawienia szkody, odpowiedzialności za działania osób trzecich, skutków zwłoki oraz możliwości dochodzenia odszkodowania przez wierzyciela. Reguluje również kwestie związane z karami umownymi oraz sytuacjami, w których dłużnik może być zwolniony z odpowiedzialności.
Art. 487.-Art. 497.
Przepisy dotyczące umów wzajemnych w Kodeksie cywilnym, które regulują zasady wykonania i skutków niewykonania zobowiązań wynikających z takich umów. Zawierają m.in. zasady dotyczące jednoczesności świadczeń, możliwości odstąpienia od umowy w przypadku zwłoki lub niemożliwości wykonania świadczenia, a także zasady dotyczące zwrotu świadczeń po odstąpieniu od umowy. Przepisy te określają również sytuacje, w których strony mogą wstrzymać się z wykonaniem swoich zobowiązań oraz zasady odpowiedzialności za niewykonanie umowy.
Art. 498.-Art. 508.
Przepisy dotyczące potrącenia wierzytelności oraz odnowienia zobowiązań w polskim prawie cywilnym. Zawierają zasady dotyczące wzajemnego umarzania wierzytelności, procedurę dokonywania potrącenia, a także szczególne przypadki, w których potrącenie nie jest możliwe. Dodatkowo regulują kwestie związane z odnowieniem zobowiązań oraz skutkami zabezpieczeń w przypadku odnowienia.
Art. 509.-Art. 518.
Przepisy dotyczące przelewu wierzytelności w Kodeksie cywilnym, które regulują zasady przenoszenia wierzytelności na osoby trzecie. Zawierają informacje o możliwości przelewu bez zgody dłużnika, skutkach przelewu, obowiązkach zbywcy oraz dłużnika, a także o odpowiedzialności zbywcy za istnienie wierzytelności. Przepisy te określają również zasady dotyczące spłaty wierzytelności przez osoby trzecie oraz wyjątki dotyczące wierzytelności związanych z dokumentami na okaziciela.
Art. 519.-Art. 525.
Przepisy dotyczące przejęcia długu, które regulują zasady, na jakich osoba trzecia może wstąpić na miejsce dłużnika, zwalniając go z zobowiązań. Zawierają szczegółowe informacje na temat umowy o przejęcie długu, wymogu zgody dłużnika i wierzyciela, formy pisemnej umowy, a także skutków przejęcia długu, w tym praw przejmującego dług oraz wygasania zabezpieczeń.
Art. 527.-Art. 534.
Przepisy dotyczące bezskuteczności czynności prawnych dłużnika dokonanych z pokrzywdzeniem wierzycieli. Zawierają zasady dotyczące możliwości żądania uznania takich czynności za bezskuteczne przez wierzycieli, warunki domniemania świadomości dłużnika oraz osoby trzeciej, a także procedury dochodzenia roszczeń w przypadku uzyskania korzyści majątkowej. Określają również terminy przedawnienia dla takich roszczeń.
Art. 535.-Art. 555.
Przepisy dotyczące umowy sprzedaży w Kodeksie cywilnym, które regulują zasady przenoszenia własności rzeczy, ustalania ceny oraz obowiązki sprzedawcy i kupującego. Zawierają informacje o sposobie wydania rzeczy, odpowiedzialności za uszkodzenia, a także szczególne przepisy dotyczące sprzedaży konsumenckiej. Obejmują również kwestie związane z kosztami wydania, zwłoką w odbiorze rzeczy oraz roszczeniami wynikającymi z umowy sprzedaży.
Art. 556.-Art. 576.
Przepisy dotyczące rękojmi w umowach sprzedaży, które regulują odpowiedzialność sprzedawcy za wady fizyczne i prawne rzeczy sprzedanej. Zawierają definicje wad, zasady dotyczące zgłaszania wad przez kupującego, uprawnienia kupującego w przypadku stwierdzenia wad, a także terminy odpowiedzialności sprzedawcy. Przepisy te różnicują prawa konsumentów i przedsiębiorców oraz określają procedury związane z wymianą lub naprawą wadliwych rzeczy.
Art. 577.-Art. 581.
Przepisy dotyczące gwarancji w polskim prawie cywilnym, które regulują zasady udzielania gwarancji przez sprzedawców oraz prawa kupujących w przypadku wad rzeczy sprzedanej. Zawierają szczegółowe informacje na temat formy oświadczenia gwarancyjnego, obowiązków gwaranta, procedur korzystania z gwarancji, a także odpowiedzialności sprzedawcy za niezgodność towaru z umową. Przepisy te określają również terminy gwarancji oraz zasady dotyczące wymiany lub naprawy wadliwych produktów.
Art. 583.-Art. 588.
Przepisy dotyczące sprzedaży na raty, które regulują zasady sprzedaży rzeczy ruchomych osobom fizycznym w ramach działalności przedsiębiorstwa. Zawierają informacje o odpowiedzialności sprzedawcy z tytułu rękojmi, możliwościach wcześniejszej spłaty rat, warunkach odstąpienia od umowy w przypadku opóźnień w płatnościach oraz zastosowaniu przepisów w kontekście kredytów bankowych. Przepisy te mają na celu ochronę praw kupującego oraz określenie obowiązków sprzedawcy.
Art. 589.-Art. 592.
Przepisy dotyczące zastrzeżenia własności w umowach sprzedaży rzeczy ruchomych. Określają zasady przeniesienia własności pod warunkiem zawieszającym, wymagania dotyczące formy zastrzeżenia, a także prawa sprzedawcy w przypadku uszkodzenia lub zużycia rzeczy. Zawierają również regulacje dotyczące sprzedaży na próbę oraz skutki braku oświadczenia kupującego o uznaniu przedmiotu sprzedaży za dobry.
Art. 593.-Art. 595.
Przepisy dotyczące prawa odkupu, które regulują zasady wykonywania tego prawa w umowach sprzedaży. Określają maksymalny czas trwania prawa odkupu, sposób jego wykonania oraz obowiązki stron w przypadku jego realizacji, w tym przeniesienie własności i zwrot kosztów. Zawierają również informacje o niezbywalności i niepodzielności prawa odkupu oraz o sytuacjach, w których kilku uprawnionych może skorzystać z tego prawa.
Art. 596.-Art. 602.
Przepisy dotyczące prawa pierwokupu, które regulują zasady wykonywania tego prawa w kontekście sprzedaży rzeczy. Zawierają informacje na temat warunków, w jakich prawo pierwokupu może być wykonane, obowiązków zobowiązanego do informowania uprawnionego o sprzedaży, oraz konsekwencji za niewłaściwe wykonanie umowy. Określają również, że prawo pierwokupu jest niezbywalne i niepodzielne, z wyjątkiem sytuacji przewidzianych w przepisach szczególnych.
Art. 603.-Art. 604.
Przepisy dotyczące umowy zamiany, które regulują zasady przenoszenia własności rzeczy pomiędzy stronami. Art. 603 definiuje umowę zamiany jako zobowiązanie obu stron do wymiany własności rzeczy, natomiast Art. 604 wskazuje, że do umowy zamiany stosuje się odpowiednio przepisy dotyczące sprzedaży.
Art. 605.-Art. 612.
Przepisy dotyczące umowy dostawy, które regulują zobowiązania dostawcy i odbiorcy w zakresie wytwarzania i dostarczania rzeczy. Zawierają zasady dotyczące formy umowy, odpowiedzialności za wady, procedur informacyjnych oraz możliwości odstąpienia od umowy w przypadku opóźnień lub wadliwości wykonania. Wskazują również na zastosowanie przepisów o sprzedaży w sprawach nieuregulowanych.
Art. 613.-Art. 626.
Przepisy dotyczące umowy kontraktacji w prawie cywilnym, które regulują relacje między producentami rolnymi a kontraktującymi. Zawierają zasady dotyczące zobowiązań stron, w tym wytwarzania i dostarczania produktów rolnych, odpowiedzialności za wady, warunków zwrotu zaliczek oraz przedawnienia roszczeń. Określają również obowiązki kontraktującego, takie jak nadzór nad wykonaniem umowy oraz możliwość wprowadzenia świadczeń dodatkowych. Przepisy te uwzględniają także sytuacje związane z przejściem praw i obowiązków w przypadku zmiany posiadania gospodarstwa.
Art. 627.-Art. 646.
Przepisy dotyczące umowy o dzieło w Kodeksie cywilnym, które regulują zasady zawierania, wykonywania oraz rozliczania umów o dzieło. Zawierają informacje na temat wynagrodzenia, odpowiedzialności za wady dzieła, obowiązków stron oraz możliwości odstąpienia od umowy. Obejmują również kwestie związane z dostarczaniem materiałów przez zamawiającego oraz skutkami opóźnień w wykonaniu dzieła. Przepisy te są istotne dla osób angażujących się w umowy o dzieło, zarówno wykonawców, jak i zamawiających.
Art. 647.-Art. 658.
Przepisy dotyczące umowy o roboty budowlane w Kodeksie cywilnym, które regulują zasady zawierania umów budowlanych, odpowiedzialność inwestora i wykonawcy, a także kwestie związane z podwykonawcami. Zawierają przepisy dotyczące gwarancji zapłaty, odpowiedzialności za szkody, przyjmowania robót oraz uprawnień do odstąpienia od umowy. Wskazują również na obowiązki stron w kontekście dokumentacji oraz jakości dostarczanych materiałów.
Art. 659.-Art. 679.
Przepisy dotyczące umowy najmu w Kodeksie cywilnym, które regulują prawa i obowiązki wynajmującego oraz najemcy. Zawierają zasady dotyczące zawierania umowy najmu, obowiązków stron, płatności czynszu, napraw rzeczy najętej, a także warunki wypowiedzenia umowy. Określają również zasady dotyczące odpowiedzialności za wady rzeczy oraz skutki zbycia rzeczy najętej w trakcie trwania najmu.
Art. 680.-Art. 692.
Przepisy dotyczące najmu lokali mieszkalnych, które regulują zasady zawierania umów najmu, prawa i obowiązki najemców oraz wynajmujących, a także kwestie związane z wypowiedzeniem umowy najmu. Zawierają m.in. przepisy dotyczące wspólności najmu w małżeństwie, odpowiedzialności za czynsz, warunki wypowiedzenia umowy oraz zasady dotyczące wstąpienia w stosunek najmu po śmierci najemcy.
Art. 693.-Art. 709.
Przepisy dotyczące dzierżawy w Kodeksie cywilnym, które regulują umowy dzierżawy, obowiązki wydzierżawiającego i dzierżawcy, zasady płatności czynszu oraz warunki wypowiedzenia umowy. Zawierają również przepisy dotyczące napraw, zwrotu przedmiotu dzierżawy oraz obliczania czynszu w przypadku zakończenia dzierżawy przed upływem umówionego terminu.
Art. 7091.-Art. 70918.
Przepisy dotyczące umowy leasingu w Kodeksie cywilnym, które regulują zasady zawierania, wykonywania oraz rozwiązania umowy leasingowej. Zawierają szczegółowe postanowienia dotyczące obowiązków finansującego i korzystającego, w tym odpowiedzialności za wady rzeczy, zasady płatności rat, warunki wypowiedzenia umowy oraz przeniesienia własności rzeczy po zakończeniu leasingu. Przepisy te mają na celu zapewnienie przejrzystości i ochrony praw obu stron umowy leasingowej.
Art. 710.-Art. 719.
Przepisy dotyczące umowy użyczenia, które regulują zasady korzystania z rzeczy oddanej do bezpłatnego używania. Zawierają postanowienia dotyczące odpowiedzialności użyczającego za wady rzeczy, obowiązki biorącego w zakresie użytkowania oraz zwrotu rzeczy po zakończeniu umowy. Określają również zasady dotyczące odpowiedzialności za uszkodzenia oraz przedawnienia roszczeń związanych z umową użyczenia.
Art. 720.-Art. 7241.
Przepisy dotyczące umowy pożyczki w Kodeksie cywilnym, które regulują zasady zawierania umów pożyczkowych, zarówno pieniężnych, jak i dotyczących rzeczy. Zawierają szczegółowe przepisy dotyczące warunków umowy, wysokości odsetek oraz kosztów pozaodsetkowych, a także zasady dotyczące zabezpieczeń, informowania biorcy pożyczki o kosztach oraz skutków przedterminowej spłaty. Obejmują również regulacje dotyczące odpowiedzialności dającego pożyczkę za wady przedmiotu pożyczki oraz terminy przedawnienia roszczeń związanych z umową.
Art. 725.-Art. 733.
Przepisy dotyczące umowy rachunku bankowego, które regulują prawa i obowiązki banku oraz posiadacza rachunku. Zawierają zasady dotyczące przechowywania środków pieniężnych, informowania o zmianach stanu rachunku, warunki wypowiedzenia umowy oraz terminy przedawnienia roszczeń. Przepisy te mają zastosowanie również do rachunków prowadzonych przez spółdzielcze kasy oszczędnościowo-kredytowe i nie naruszają przepisów o rozliczeniach pieniężnych.
Art. 734.-Art. 751.
Przepisy dotyczące umowy zlecenia w Kodeksie cywilnym, które regulują zasady zawierania, wykonywania oraz zakończenia umowy zlecenia. Zawierają informacje na temat wynagrodzenia, odpowiedzialności przyjmującego zlecenie, możliwości powierzenia wykonania zlecenia osobie trzeciej, a także zasady wypowiedzenia umowy. Określają również skutki wygaśnięcia zlecenia oraz przedawnienie roszczeń związanych z umową.
Art. 752.-Art. 757.
Przepisy dotyczące prowadzenia cudzej sprawy bez zlecenia, które określają obowiązki i odpowiedzialność osoby prowadzącej taką sprawę. Zawierają zasady dotyczące działania w interesie osoby, której sprawa jest prowadzona, obowiązek informowania jej o działaniach, a także regulacje dotyczące zwrotu wydatków oraz odpowiedzialności za szkody w przypadku działania wbrew woli tej osoby. Przepisy te również wskazują na możliwość uzyskania potwierdzenia skutków zlecenia oraz zasady dotyczące ratowania dóbr w sytuacjach zagrożenia.
Art. 758.-Art. 7649.
Przepisy dotyczące umowy agencyjnej w Kodeksie cywilnym, które regulują zasady współpracy między agentem a dającym zlecenie. Zawierają definicje umowy agencyjnej, zasady wynagradzania agenta, obowiązki stron, a także przepisy dotyczące wypowiedzenia umowy oraz ewentualnych roszczeń po jej rozwiązaniu. Wskazują również na kwestie związane z lojalnością, odpowiedzialnością agenta oraz ograniczeniami działalności konkurencyjnej po zakończeniu umowy.
Art. 765.-Art. 773.
Przepisy dotyczące umowy komisu, które regulują relacje między komisantem a komitentem. Zawierają zasady dotyczące obowiązków komisanta, w tym wydawania uzyskanych dóbr, odpowiedzialności za wady rzeczy, a także zasady dotyczące prowizji oraz zabezpieczeń roszczeń. Określają również sytuacje, w których komisant może działać w interesie komitenta oraz zasady dotyczące sprzedaży rzeczy w przypadku ich narażenia na zepsucie.
Art. 774.-Art. 775.
Przepisy dotyczące umowy przewozu, w których określono obowiązki przewoźnika oraz zasady stosowania przepisów w kontekście różnych rodzajów transportu. Artykuły te regulują zobowiązania przewoźnika do przewozu osób lub rzeczy za wynagrodzeniem oraz wskazują na możliwość stosowania odrębnych przepisów w przypadku specyficznych form transportu.
Art. 776.-Art. 778.
Przepisy dotyczące umowy przewozu osób, które określają obowiązki przewoźnika w zakresie zapewnienia bezpieczeństwa, higieny i wygód podróżnym. Zawierają również zasady odpowiedzialności przewoźnika za bagaż oraz terminy przedawnienia roszczeń związanych z umową przewozu.
Art. 779.-Art. 793.
Przepisy dotyczące umowy przewozu rzeczy, które regulują obowiązki wysyłającego i przewoźnika, a także prawa i obowiązki odbiorcy przesyłki. Zawierają szczegółowe informacje na temat wymaganych danych w liście przewozowym, odpowiedzialności przewoźnika za uszkodzenia przesyłek, procedur w przypadku odmowy przyjęcia przesyłki przez odbiorcę oraz zasady dotyczące przedawnienia roszczeń wynikających z umowy przewozu.
Art. 794.-Art. 804.
Przepisy dotyczące umowy spedycji w Kodeksie cywilnym, które regulują prawa i obowiązki spedytora oraz zasady odpowiedzialności związanej z przewozem przesyłek. Zawierają informacje o umowie spedycji, odpowiedzialności spedytora za przewoźników, zasadach dochodzenia roszczeń oraz terminach przedawnienia. Przepisy te określają również zasady zabezpieczenia roszczeń oraz odpowiedzialność za uszkodzenia lub utratę przesyłek.
Art. 805.-Art. 820.
Przepisy dotyczące umowy ubezpieczenia w Kodeksie cywilnym, które regulują zasady zawierania umów ubezpieczeniowych, obowiązki stron umowy, a także zasady dotyczące świadczeń ubezpieczyciela. Zawierają m.in. definicje umowy ubezpieczenia, zasady dotyczące ważności umowy, obowiązki informacyjne ubezpieczającego, terminy wypłaty świadczeń oraz przepisy dotyczące przedawnienia roszczeń. Przepisy te mają na celu ochronę interesów zarówno ubezpieczających, jak i ubezpieczonych, a także określają zasady odpowiedzialności ubezpieczyciela.
Art. 821.-Art. 828.
Przepisy dotyczące ubezpieczeń majątkowych i odpowiedzialności cywilnej w Kodeksie cywilnym. Zawierają definicje przedmiotu ubezpieczenia, zasady dotyczące umowy ubezpieczenia odpowiedzialności cywilnej, przenoszenie praw i obowiązków w przypadku zbycia przedmiotu ubezpieczenia, ustalanie sumy ubezpieczenia oraz odpowiedzialności ubezpieczyciela. Reguluje również obowiązki ubezpieczającego w razie szkody oraz zasady przechodzenia roszczeń na ubezpieczyciela po wypłacie odszkodowania.
Art. 829.-Art. 834.
Przepisy dotyczące ubezpieczeń osobowych w Kodeksie cywilnym, które regulują zasady zawierania umów ubezpieczenia na życie oraz ubezpieczeń od następstw nieszczęśliwych wypadków. Zawierają informacje o odpowiedzialności ubezpieczyciela, możliwościach wypowiedzenia umowy przez ubezpieczającego, wskazywaniu osób uprawnionych do otrzymania sumy ubezpieczenia, a także skutkach samobójstwa oraz nieprawdziwych informacji podanych przy zawieraniu umowy.
Art. 835.-Art. 845.
Przepisy dotyczące umowy przechowania, które regulują prawa i obowiązki przechowawcy oraz składającego. Zawierają zasady dotyczące wynagrodzenia za przechowanie, sposobu i miejsca przechowywania rzeczy, a także odpowiedzialności przechowawcy za ewentualne uszkodzenia lub utratę rzeczy. Określają również zasady dotyczące zwrotu rzeczy oraz sytuacje, w których przechowawca może oddać rzecz innej osobie.
Art. 846.-Art. 852.
Przepisy dotyczące odpowiedzialności utrzymujących zarobkowo hotele i podobne zakłady za utratę lub uszkodzenie rzeczy wniesionych przez gości. Zawierają zasady odpowiedzialności, terminy zgłaszania szkód, ograniczenia odpowiedzialności oraz regulacje dotyczące przechowywania wartościowych przedmiotów. Określają również prawo zastawu na rzeczach wniesionych oraz terminy przedawnienia roszczeń związanych z działalnością hotelową. Przepisy te mają zastosowanie także do zakładów kąpielowych.
Art. 853.-Art. 8599.
Przepisy dotyczące umowy składu, które regulują zasady przechowywania rzeczy ruchomych przez przedsiębiorcę składowego. Zawierają postanowienia dotyczące obowiązków przedsiębiorcy, odpowiedzialności za szkody, procedur związanych z odbiorem rzeczy oraz warunków wypowiedzenia umowy. Określają również zasady dotyczące ubezpieczenia rzeczy, zabezpieczenia roszczeń oraz terminy przedawnienia roszczeń związanych z umową składu.
Art. 860.-Art. 875.
Przepisy dotyczące umowy spółki w Kodeksie cywilnym, które regulują zasady tworzenia, funkcjonowania oraz rozwiązania spółek. Zawierają informacje o wkładach wspólników, ich prawach i obowiązkach, odpowiedzialności za zobowiązania spółki, podziale zysków oraz procedurze wystąpienia wspólnika ze spółki. Przepisy te określają również zasady dotyczące dziedziczenia udziałów w spółce oraz postępowania w przypadku rozwiązania spółki.
Art. 876.-Art. 887.
Przepisy dotyczące umowy poręczenia w Kodeksie cywilnym, które regulują zasady odpowiedzialności poręczyciela za długi dłużnika. Zawierają informacje na temat formy umowy, zakresu zobowiązań poręczyciela, jego praw i obowiązków, a także sytuacji, w których poręczenie może wygasnąć. Przepisy te określają również zasady dotyczące komunikacji między poręczycielem, dłużnikiem i wierzycielem oraz skutki niewłaściwego wykonania zobowiązań.
Art. 888.-Art. 902.
Przepisy dotyczące umowy darowizny w Kodeksie cywilnym, które regulują zasady dokonywania darowizn, odpowiedzialność darczyńcy oraz obdarowanego, a także warunki odwołania darowizny. Zawierają informacje na temat formy umowy, skutków niewykonania zobowiązań, możliwości wprowadzenia poleceń przez darczyńcę oraz zasady dotyczące niewdzięczności obdarowanego. Przepisy te określają również sytuacje, w których darowizna może być odwołana oraz obowiązki obdarowanego w przypadku niedostatku darczyńcy.
Art. 9021.-Art. 9022.
Przepisy dotyczące umowy przekazania nieruchomości, w których określono zasady przenoszenia własności nieruchomości na gminę lub Skarb Państwa. Zawierają regulacje dotyczące nieodpłatnego przekazania nieruchomości oraz odpowiedzialności właściciela za wady nieruchomości, w przypadku braku odmiennych ustaleń między stronami.
Art. 903.-Art. 907.
Przepisy dotyczące umowy renty w Kodeksie cywilnym, które regulują zasady zawierania, płatności oraz charakterystykę świadczeń okresowych. Zawierają informacje na temat formy umowy, terminów płatności, a także odniesienia do przepisów o sprzedaży i darowiźnie w kontekście renty. Dodatkowo, przepisy te przewidują możliwość zmiany warunków renty w przypadku zmiany okoliczności.
Art. 908.-Art. 916.
Przepisy dotyczące umowy o dożywocie, które regulują zasady przeniesienia własności nieruchomości w zamian za zapewnienie dożywotniego utrzymania zbywcy. Zawierają szczegółowe postanowienia dotyczące obowiązków nabywcy, obciążenia nieruchomości prawem dożywocia, a także zasady dotyczące zmiany warunków umowy oraz możliwości jej unieważnienia w przypadku niewypłacalności dożywotnika. Przepisy te określają również, że prawo dożywocia jest niezbywalne i mogą być stosowane w odniesieniu do różnych form zabezpieczeń dla zbywcy.
Art. 917.-Art. 918.
Przepisy dotyczące ugody w prawie cywilnym, które regulują zasady zawierania ugód między stronami w celu rozwiązania sporów lub niepewności dotyczących roszczeń. Artykuły te określają, jak ugoda wpływa na stosunki prawne oraz warunki, w jakich możliwe jest uchwałanie się od skutków prawnych ugody, szczególnie w kontekście błędu i dobrej wiary stron.
Art. 919.-Art. 921.
Przepisy dotyczące publicznego przyrzeczenia nagrody, które regulują zasady przyznawania nagród za wykonanie określonych czynności. Zawierają informacje o obowiązku dotrzymania przyrzeczenia, możliwości jego odwołania, zasadach przyznawania nagrody w przypadku wykonania czynności przez kilka osób oraz wymogu określenia terminu ubiegania się o nagrodę. Określają również zasady dotyczące nabycia własności nagrodzonego dzieła.
Art. 9211.-Art. 9215.
Przepisy dotyczące przekazu w kodeksie cywilnym, które regulują zasady dotyczące przekazywania świadczeń przez osoby trzecie. Zawierają informacje na temat uprawnień odbiorcy przekazu, obowiązków przekazanego oraz możliwości odwołania przekazu przez przekazującego. Określają również zasady dotyczące przedawnienia roszczeń oraz skutków umorzenia długu w kontekście przekazu.
Art. 9216.-Art. 92116.
Przepisy dotyczące papierów wartościowych w Kodeksie cywilnym, które regulują zasady związane z obiegiem, przenoszeniem praw oraz obowiązkami dłużników i wierzycieli w kontekście papierów wartościowych. Zawierają informacje na temat legitymacji, indosu, umarzania dokumentów oraz zasadności świadczenia w przypadku wątpliwości co do właściciela dokumentu. Przepisy te obejmują również znaki legitymacyjne oraz prawa inne niż wierzytelności.
Art. 922.-Art. 930.
Przepisy dotyczące dziedziczenia w Kodeksie cywilnym, które regulują zasady przechodzenia praw i obowiązków majątkowych zmarłego na spadkobierców. Zawierają informacje o otwarciu spadku, nabywaniu spadku, dziedziczeniu ustawowym oraz warunkach, które mogą prowadzić do uznania spadkobiercy za niegodnego dziedziczenia. Przepisy te określają również prawa bliskich zmarłego oraz zasady dotyczące testamentów i możliwości ich podważania.
Art. 931.-Art. 940.
Przepisy dotyczące dziedziczenia ustawowego w Kodeksie cywilnym, które określają zasady powołania do spadku oraz kolejność dziedziczenia w przypadku braku testamentu. Zawierają regulacje dotyczące dziedziczenia przez dzieci, małżonka, rodziców, rodzeństwo oraz dziadków spadkodawcy, a także zasady dotyczące przysposobienia i wyłączenia małżonka od dziedziczenia. Przepisy te precyzują również zasady podziału spadku oraz prawa do roszczeń alimentacyjnych dla dziadków.
Art. 941.-Art. 948.
Przepisy dotyczące testamentów w Kodeksie cywilnym, które regulują zasady sporządzania, odwoływania oraz interpretacji testamentów. Zawierają informacje o zdolności do czynności prawnych spadkodawcy, warunkach ważności testamentu, oraz zasadach dotyczących odwołania i interpretacji woli spadkodawcy.
Art. 950.-Art. 958.
Przepisy dotyczące sporządzania testamentów w Kodeksie cywilnym, które określają różne formy i zasady tworzenia testamentów, w tym testamentów notarialnych, ustnych oraz szczególnych, takich jak testamenty wojskowe. Zawierają również regulacje dotyczące świadków przy sporządzaniu testamentów, ich zdolności oraz sytuacji, w których testamenty mogą być uznane za nieważne. Przepisy te mają na celu zapewnienie prawidłowego i zgodnego z prawem wyrażenia ostatniej woli spadkodawcy.
Art. 959.-Art. 967.
Przepisy dotyczące powoływania spadkobierców testamentowych w polskim prawie spadkowym. Zawierają zasady dotyczące powoływania osób do spadku, określania ich udziałów, a także zasady dotyczące warunków i terminów w testamentach. Regulują również kwestie związane z podstawieniem spadkobiercy oraz przyrostem udziałów w przypadku, gdy jeden ze spadkobierców nie może lub nie chce przyjąć spadku. Dodatkowo, przepisy te odnoszą się do obowiązków spadkobierców wobec osób uprawnionych do alimentów.
Art. 968.-Art. 981.
Przepisy dotyczące zapisów testamentowych w polskim prawie cywilnym, które regulują zasady dotyczące obciążania spadkobierców i zapisobierców określonymi świadczeniami majątkowymi. Zawierają informacje na temat możliwości ustanawiania zapisów, ich wykonania, odpowiedzialności za wady rzeczy oraz przedawnienia roszczeń związanych z zapisami. Przepisy te określają również zasady dotyczące dalszych zapisów oraz sytuacji, w których zapisobierca może być zwolniony z obowiązku wykonania zapisu.
Art. 9811.-Art. 9816.
Przepisy dotyczące zapisu windykacyjnego w polskim prawie spadkowym, które regulują zasady dotyczące testamentów sporządzonych w formie aktu notarialnego. Zawierają definicje zapisu windykacyjnego, warunki jego skuteczności oraz zasady dotyczące obciążania zapisami zwykłymi. Określają również, że w przypadku braku regulacji w tym rozdziale stosuje się przepisy o zapisie zwykłym.
Art. 982.-Art. 985.
Przepisy dotyczące poleceń w testamencie, które określają zasady nałożenia obowiązków na spadkobierców lub zapisobierców. Zawierają regulacje dotyczące możliwości włożenia na spadkobiercę obowiązku działania lub zaniechania, prawa zapisobiercy do wstrzymania się z wykonaniem polecenia, oraz zasady dotyczące wykonania polecenia przez spadkobiercę w przypadku, gdy zapisobierca nie może lub nie chce go wykonać. Dodatkowo, przepisy te wskazują, kto może żądać wykonania polecenia, w tym spadkobierców oraz organy państwowe w przypadku interesu społecznego.
Art. 986.-Art. 9901.
Przepisy dotyczące wykonawcy testamentu w polskim prawie spadkowym. Określają zasady powoływania wykonawcy testamentu, jego obowiązki w zarządzaniu majątkiem spadkowym, a także procedury związane z przyjęciem lub odmową przyjęcia tego obowiązku. Zawierają również regulacje dotyczące wzajemnych roszczeń między spadkobiercami a wykonawcą oraz możliwość zwolnienia wykonawcy z jego obowiązków przez sąd.
Art. 991.-Art. 1011.
Przepisy dotyczące zachowku w polskim prawie spadkowym, które regulują prawa osób uprawnionych do zachowku, w tym zstępnych, małżonków i rodziców spadkodawcy. Zawierają zasady obliczania zachowku, uwzględniania darowizn oraz zapisów windykacyjnych, a także kwestie związane z wydziedziczeniem. Przepisy te określają również odpowiedzialność spadkobierców za zaspokojenie roszczeń z tytułu zachowku oraz terminy przedawnienia tych roszczeń.
Art. 1012.-Art. 1024.
Przepisy dotyczące przyjęcia i odrzucenia spadku w Kodeksie cywilnym, które regulują zasady związane z dziedziczeniem. Zawierają informacje na temat różnych form przyjęcia spadku (proste, z dobrodziejstwem inwentarza), terminów składania oświadczeń, możliwości uchwały oświadczeń w przypadku błędu lub groźby, a także skutków odrzucenia spadku, w tym ochrony wierzycieli. Przepisy te określają również zasady dotyczące spadkobierców oraz sytuacje, w których Skarb Państwa i gmina nie mogą odrzucić spadku.
Art. 1025.-Art. 10291.
Przepisy dotyczące stwierdzenia nabycia spadku oraz poświadczenia dziedziczenia, które regulują procedury związane z dziedziczeniem. Zawierają zasady dotyczące stwierdzenia nabycia spadku przez sąd, domniemania spadkobiercy, terminy związane z otwarciem spadku, a także prawa spadkobierców w relacji do osób trzecich oraz roszczenia dotyczące wydania spadku. Dodatkowo, przepisy te odnoszą się również do zapisów windykacyjnych.
Art. 1030.-Art. 10343.
Przepisy dotyczące odpowiedzialności spadkobierców za długi spadkowe w Kodeksie cywilnym. Zawierają zasady dotyczące przyjęcia spadku, w tym odpowiedzialności za długi w zależności od formy przyjęcia (proste przyjęcie lub z dobrodziejstwem inwentarza), składania wykazu inwentarza oraz rozliczeń między spadkobiercami. Określają również zasady dotyczące solidarnych i proporcjonalnych odpowiedzialności za długi spadkowe oraz ograniczenia tej odpowiedzialności w zależności od wartości stanu czynnego spadku.
Art. 1035.-Art. 1046.
Przepisy dotyczące działu spadku w Kodeksie cywilnym, które regulują zasady dotyczące podziału majątku spadkowego pomiędzy spadkobierców. Zawierają informacje na temat wspólności majątku spadkowego, możliwości rozporządzania udziałami, formy umowy o dział spadku, zasad zaliczenia darowizn i zapisów windykacyjnych na schedę spadkową, a także odpowiedzialności spadkobierców za wady fizyczne i prawne po dokonaniu podziału.
Art. 1047.-Art. 1057.
Przepisy dotyczące dziedziczenia i zbywania spadków w Kodeksie cywilnym. Zawierają zasady dotyczące nieważności umowy o spadek po osobie żyjącej, zrzeczenia się dziedziczenia, zbywania spadku oraz odpowiedzialności nabywcy za długi spadkowe. Określają również formę umów związanych z dziedziczeniem oraz skutki prawne zbycia spadku.
Art. 1058.-Art. 1087.
Przepisy dotyczące dziedziczenia gospodarstw rolnych w Kodeksie cywilnym, które regulują zasady dziedziczenia gruntów rolnych oraz warunki, jakie muszą spełniać spadkobiercy, aby nabyć prawo do gospodarstwa. Zawierają informacje o dziedziczeniu przez osoby pracujące w rolnictwie, przygotowanie zawodowe, a także zasady dotyczące podziału spadku, odpowiedzialności za długi spadkowe oraz zasady dotyczące wkładów gruntowych w rolniczych spółdzielniach produkcyjnych.    """
    user_prompt_template = """
    Question:
    {question_dict}
    """

    def __init__(self, model="gpt-4o-mini", temperature=0):
        self.model = model
        self.temperature = temperature

        llm = ChatOpenAI(model=model, temperature=temperature)
        prompt = ChatPromptTemplate.from_messages([
            ("system", self.system_prompt),
            ("user", "{formatted_question}")
        ])
        output_parser = StrOutputParser()
        self.chain = prompt | llm | output_parser

    def generate_article_knowledge(self, question_dict):
        formatted_question = self.user_prompt_template.format(question_dict=format_question(question_dict))
        return self.chain.invoke({"formatted_question": formatted_question})
